version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 8888:8888
    networks:
      - service_network
    restart: always

networks:
  service_network:
    driver: bridge
