version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 8888:8888
    networks:
      - service_network
    restart: always

  # nginx-proxy:
  #   container_name: nginx-proxy
  #   depends_on:
  #     - db
  #     - backend
  #     - frontend
  #   image: nginx:latest
  #   ports:
  #     - '80:80'
  #     - '433:433'
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  #   restart: always
  #   networks:
  #     - service_network

networks:
  service_network:
    driver: bridge
