name: Lightsail Auto Deploy

on:
  workflow_run:
    workflows: [Build And Push Docker Image]
    types:
      - completed

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Access to Lightsail
        run: echo "${{ secrets.LIGHTSAIL_ACCESS_KEY }}" > ./accesskey.pem
      - name: Change Access Key Permission
        run: chmod 600 ./accesskey.pem
      - name: Connect to Lightsail
        run: |
          ssh -i ./accesskey.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.LIGHTSAIL_IP }} "\
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest \
          && sudo docker stop backend \
          && sudo docker rm backend \
          && sudo docker run -d --name backend -p ${{ secrets.DOCKER_PORT }}:${{ secrets.DOCKER_PORT }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest \
          && exit"
